---
- hosts: all
  remote_user: ansible
  become: true
  become_user: root
  tasks:
  - name: Ensure nginx installed
    ansible.builtin.apt:
      name: nginx
      update_cache: yes
      state: present
