---
- name: Preset node
  hosts: all
  remote_user: ansible
  become: yes
  become_user: root
  tasks:

    - name: Show params
      debug:
        msg: user {{ user }}, port_prefix {{ port_prefix }}, go_version {{ go_version }}

    - name: "UFW: allow 22 tcp"
      community.general.ufw: rule=allow port=22 proto=tcp

    - name: "UFW: set default policy"
      community.general.ufw: state=enabled policy=reject

    - name: "UFW: show status"
      ansible.builtin.command: ufw status verbose
